remote_theme: pmarsceill/just-the-docs

# jekyll
title: beatmania IIDX guide [iidx.org]
description: iidx.org - a modern guide for beatmania IIDX in English
future: true

# for just-the-docs

ga_tracking: UA-196434487-1
ga_tracking_anonymize_ip: true

back_to_top: true
back_to_top_text: "Back to top"

color_scheme: custom

plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag