remote_theme: pmarsceill/just-the-docs

# jekyll
title: iidx.org
description: A modern guide for beatmania IIDX... in English!
future: true

# for just-the-docs

ga_tracking: UA-196434487-1
ga_tracking_anonymize_ip: true

aux_links:
  "see on GitHub":
    - "//github.com/minsang-github/iidxguide"

back_to_top: true
back_to_top_text: "Back to top"

plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from
  - jekyll-sitemap