source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
gem "webrick", "~> 1.7"
gem "just-the-docs"
gem "jekyll-remote-theme"
gem 'jekyll-redirect-from'
gem "jekyll-sitemap"
gem "jekyll-seo-tag"